import { ShopingCartProvider } from "@/context/ShopingCartContext";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const montserrat = localFont({
  src: [
    { path: "./fonts/Montserrat-Regular.woff2", weight: "400" },
    { path: "./fonts/Montserrat-Medium.woff2", weight: "500" },
    { path: "./fonts/Montserrat-SemiBold.woff2", weight: "600" },
    { path: "./fonts/Montserrat-Bold.woff2", weight: "700" },
    { path: "./fonts/Montserrat-Black.woff2", weight: "900" },
  ],
  variable: "--font-montserrat",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="uk-UA">
      <body
        className={`${montserrat.variable} flex min-h-screen flex-col antialiased`}
      >
        <ShopingCartProvider>{children}</ShopingCartProvider>
      </body>
    </html>
  );
}
